spring:
  application:
    name: quize-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/quizedb

server:
  port: 9092

  # ===== Service Discovery Client (Eureka) Config =====
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/